/**
 * Analytics PDF Export Utility
 * Task 0057: Export analytics report as PDF
 *
 * Note: This is a simplified implementation using browser print.
 * For production, consider using libraries like jsPDF or react-pdf
 */

/**
 * Escape HTML to prevent XSS attacks
 */
function escapeHtml(text: string | number): string {
  const stringText = String(text);
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return stringText.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Generate HTML content for PDF report
 */
export function generateAnalyticsReportHTML(
  kpis: any,
  dateRange: { start: Date; end: Date }
): string {
  const startDate = dateRange.start.toLocaleDateString();
  const endDate = dateRange.end.toLocaleDateString();
  const generatedDate = new Date().toLocaleString();

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Analytics Report - The Puppy Day</title>
  <style>
    @media print {
      @page {
        margin: 1in;
      }
    }
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #434E54;
    }
    h1 {
      color: #434E54;
      border-bottom: 3px solid #434E54;
      padding-bottom: 10px;
    }
    h2 {
      color: #434E54;
      margin-top: 30px;
      border-bottom: 1px solid #E5E7EB;
      padding-bottom: 5px;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
    }
    .date-range {
      text-align: center;
      font-size: 14px;
      color: #6B7280;
      margin-bottom: 20px;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin: 20px 0;
    }
    .kpi-card {
      border: 1px solid #E5E7EB;
      border-radius: 8px;
      padding: 15px;
      background: #F9FAFB;
    }
    .kpi-label {
      font-size: 12px;
      color: #6B7280;
      margin-bottom: 5px;
    }
    .kpi-value {
      font-size: 28px;
      font-weight: bold;
      color: #434E54;
      margin-bottom: 10px;
    }
    .kpi-change {
      font-size: 14px;
    }
    .positive {
      color: #10b981;
    }
    .negative {
      color: #ef4444;
    }
    .footer {
      margin-top: 50px;
      text-align: center;
      font-size: 12px;
      color: #6B7280;
      border-top: 1px solid #E5E7EB;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Analytics Report</h1>
    <div class="subtitle">The Puppy Day - Dog Grooming Analytics</div>
  </div>

  <div class="date-range">
    Report Period: <strong>${startDate}</strong> to <strong>${endDate}</strong><br>
    Generated: ${generatedDate}
  </div>

  <h2>Key Performance Indicators</h2>
  <div class="kpi-grid">
    ${generateKPICard('Total Revenue', kpis.total_revenue)}
    ${generateKPICard('Total Appointments', kpis.total_appointments)}
    ${generateKPICard('Avg Booking Value', kpis.avg_booking_value)}
    ${generateKPICard('Retention Rate', kpis.retention_rate)}
    ${generateKPICard('Review Generation', kpis.review_generation_rate)}
    ${generateKPICard('Waitlist Fill Rate', kpis.waitlist_fill_rate)}
  </div>

  <div class="footer">
    <p>This report was automatically generated by The Puppy Day Analytics Dashboard</p>
    <p>14936 Leffingwell Rd, La Mirada, CA 90638 | (657) 252-2903</p>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate HTML for a single KPI card
 */
function generateKPICard(label: string, kpi: any): string {
  const formattedValue = formatKPIValue(kpi.value, kpi.format);
  const changeClass = kpi.change > 0 ? 'positive' : kpi.change < 0 ? 'negative' : '';
  const changeSymbol = kpi.change > 0 ? '+' : '';

  return `
    <div class="kpi-card">
      <div class="kpi-label">${escapeHtml(label)}</div>
      <div class="kpi-value">${escapeHtml(formattedValue)}</div>
      <div class="kpi-change ${changeClass}">
        ${changeSymbol}${escapeHtml(kpi.change.toFixed(1))}% vs previous period
      </div>
    </div>
  `;
}

/**
 * Format KPI value based on format type
 */
function formatKPIValue(value: number, format: 'currency' | 'number' | 'percentage'): string {
  if (format === 'currency') {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  } else if (format === 'percentage') {
    return `${value.toFixed(1)}%`;
  } else {
    return new Intl.NumberFormat('en-US').format(value);
  }
}

/**
 * Export analytics report as PDF using browser print
 */
export function exportAnalyticsPDF(kpis: any, dateRange: { start: Date; end: Date }): void {
  const html = generateAnalyticsReportHTML(kpis, dateRange);

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to download the PDF report');
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();

  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
      // Close after printing (user can cancel)
      setTimeout(() => {
        printWindow.close();
      }, 100);
    }, 500);
  };
}
