module.exports = {
  apps: [{
    name: 'thepuppyday',
    script: '.next/standalone/server.js',
    cwd: '/var/www/html/thepuppyday',
    node_args: '--max-old-space-size=600',
    env: {
      NODE_ENV: 'production',
      PORT: 3001,
      HOSTNAME: '127.0.0.1',
      TZ: 'America/Los_Angeles',
    },
    instances: 1,
    exec_mode: 'fork',
    max_memory_restart: '700M',
    autorestart: true,
    max_restarts: 10,
    restart_delay: 5000,
    kill_timeout: 5000,
    listen_timeout: 10000,
    error_file: '/var/log/pm2/thepuppyday-error.log',
    out_file: '/var/log/pm2/thepuppyday-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
  }],
};
